"""
Marketing Plan PDF Report Generator
Generates professional PDF reports with text, tables, and charts from JSON data.
"""
import json
import sys
import os
import subprocess

def ensure_deps():
    for pkg in ['reportlab', 'matplotlib']:
        try:
            __import__(pkg)
        except ImportError:
            subprocess.check_call([sys.executable, "-m", "pip", "install", pkg])

ensure_deps()

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, Image, KeepTogether
)
from reportlab.graphics.shapes import Drawing, Rect, String
from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics.charts.barcharts import VerticalBarChart
from reportlab.graphics import renderPDF

# ── Color Palette ──
PRIMARY = colors.HexColor("#1a1a2e")
SECONDARY = colors.HexColor("#16213e")
ACCENT = colors.HexColor("#0f3460")
HIGHLIGHT = colors.HexColor("#e94560")
TEAL = colors.HexColor("#00d2ff")
WHITE = colors.HexColor("#ffffff")
LIGHT_GRAY = colors.HexColor("#f0f0f0")
MEDIUM_GRAY = colors.HexColor("#cccccc")
DARK_TEXT = colors.HexColor("#2c3e50")
CHART_COLORS = [
    colors.HexColor("#667eea"), colors.HexColor("#764ba2"),
    colors.HexColor("#f093fb"), colors.HexColor("#00d2ff"),
    colors.HexColor("#43e97b"), colors.HexColor("#fa709a"),
]


def load_data(json_path):
    with open(json_path, "r", encoding="utf-8") as f:
        return json.load(f)


def get_styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='CoverTitle', fontName='Helvetica-Bold', fontSize=32, textColor=WHITE, alignment=TA_CENTER, spaceAfter=20))
    styles.add(ParagraphStyle(name='CoverSub', fontName='Helvetica', fontSize=14, textColor=LIGHT_GRAY, alignment=TA_CENTER, spaceAfter=10))
    styles.add(ParagraphStyle(name='SectionTitle', fontName='Helvetica-Bold', fontSize=20, textColor=ACCENT, spaceBefore=24, spaceAfter=12, borderWidth=0, borderPadding=6))
    styles.add(ParagraphStyle(name='SubSection', fontName='Helvetica-Bold', fontSize=14, textColor=DARK_TEXT, spaceBefore=16, spaceAfter=8))
    styles.add(ParagraphStyle(name='BodyText2', fontName='Helvetica', fontSize=10, textColor=DARK_TEXT, alignment=TA_JUSTIFY, spaceAfter=8, leading=14))
    styles.add(ParagraphStyle(name='SmallBold', fontName='Helvetica-Bold', fontSize=10, textColor=DARK_TEXT, spaceAfter=4))
    styles.add(ParagraphStyle(name='TableHeader', fontName='Helvetica-Bold', fontSize=10, textColor=WHITE, alignment=TA_CENTER))
    styles.add(ParagraphStyle(name='TableCell', fontName='Helvetica', fontSize=9, textColor=DARK_TEXT, alignment=TA_LEFT))
    return styles


def header_footer(canvas, doc):
    canvas.saveState()
    # Header line
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(2)
    canvas.line(50, A4[1] - 40, A4[0] - 50, A4[1] - 40)
    # Footer
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(MEDIUM_GRAY)
    canvas.drawCentredString(A4[0] / 2, 25, f"Page {doc.page}")
    canvas.drawString(50, 25, "Marketing Plan Report — Generated by BrandFlow")
    canvas.restoreState()


def build_cover_page(data, styles):
    elements = []
    elements.append(Spacer(1, 2 * inch))

    # Cover background box
    d = Drawing(450, 200)
    d.add(Rect(0, 0, 450, 200, fillColor=PRIMARY, strokeColor=None, rx=15, ry=15))
    d.add(String(225, 140, data["company"]["name"], fontSize=36, fillColor=WHITE, fontName="Helvetica-Bold", textAnchor="middle"))
    d.add(String(225, 105, "Marketing Plan", fontSize=18, fillColor=TEAL, fontName="Helvetica", textAnchor="middle"))
    d.add(String(225, 70, f"Fiscal Year {data['plan_year']}", fontSize=14, fillColor=LIGHT_GRAY, fontName="Helvetica", textAnchor="middle"))
    d.add(String(225, 40, data["objective"][:80] + "...", fontSize=9, fillColor=MEDIUM_GRAY, fontName="Helvetica", textAnchor="middle"))
    elements.append(d)

    elements.append(Spacer(1, 0.5 * inch))
    authors_text = " | ".join([f"{a['name']} ({a['email']})" for a in data["authors"]])
    elements.append(Paragraph(f"<b>Authors:</b> {authors_text}", styles['BodyText2']))
    elements.append(PageBreak())
    return elements


def build_toc(styles):
    elements = []
    elements.append(Paragraph("Table of Contents", styles['SectionTitle']))
    sections = ["Business Summary", "SWOT Analysis", "Business Initiatives", "Target Market",
                 "Competitive Analysis", "Market Strategy", "Budget", "Marketing Channels", "Marketing Technology"]
    for i, s in enumerate(sections, 1):
        elements.append(Paragraph(f"{i}. {s}", styles['SubSection']))
    elements.append(PageBreak())
    return elements


def build_business_summary(data, styles):
    elements = []
    elements.append(Paragraph("1. Business Summary", styles['SectionTitle']))
    c = data["company"]
    elements.append(Paragraph(f"<b>{c['name']}</b> is headquartered in {c['hq_location']}.", styles['BodyText2']))
    elements.append(Paragraph(f"<b>Mission:</b> {c['mission']}", styles['BodyText2']))
    elements.append(Spacer(1, 12))

    elements.append(Paragraph("Marketing Leaders", styles['SubSection']))
    for leader in data["marketing_leaders"]:
        elements.append(Paragraph(f"<b>{leader['name']}</b> — {leader['title']}", styles['SmallBold']))
        elements.append(Paragraph(leader["bio"], styles['BodyText2']))
    elements.append(Spacer(1, 12))
    return elements


def build_swot(data, styles):
    elements = []
    elements.append(Paragraph("2. SWOT Analysis", styles['SectionTitle']))
    swot = data["swot"]

    def fmt(items):
        return Paragraph("<br/>".join([f"• {i}" for i in items]), styles['TableCell'])

    table_data = [
        [Paragraph("<b>Strengths</b>", styles['TableHeader']), Paragraph("<b>Weaknesses</b>", styles['TableHeader'])],
        [fmt(swot["strengths"]), fmt(swot["weaknesses"])],
        [Paragraph("<b>Opportunities</b>", styles['TableHeader']), Paragraph("<b>Threats</b>", styles['TableHeader'])],
        [fmt(swot["opportunities"]), fmt(swot["threats"])],
    ]
    t = Table(table_data, colWidths=[240, 240])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, 0), colors.HexColor("#27ae60")),
        ('BACKGROUND', (1, 0), (1, 0), colors.HexColor("#e74c3c")),
        ('BACKGROUND', (0, 2), (0, 2), colors.HexColor("#3498db")),
        ('BACKGROUND', (1, 2), (1, 2), colors.HexColor("#e67e22")),
        ('BACKGROUND', (0, 1), (0, 1), colors.HexColor("#eafaf1")),
        ('BACKGROUND', (1, 1), (1, 1), colors.HexColor("#fdedec")),
        ('BACKGROUND', (0, 3), (0, 3), colors.HexColor("#ebf5fb")),
        ('BACKGROUND', (1, 3), (1, 3), colors.HexColor("#fef9e7")),
        ('GRID', (0, 0), (-1, -1), 1, MEDIUM_GRAY),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
    ]))
    elements.append(t)
    elements.append(PageBreak())
    return elements


def build_initiatives(data, styles):
    elements = []
    elements.append(Paragraph("3. Business Initiatives", styles['SectionTitle']))
    for i, init in enumerate(data["initiatives"], 1):
        table_data = [
            [Paragraph(f"<b>Initiative {i}: {init['name']}</b>", styles['TableHeader']), ""],
            [Paragraph("<b>Description</b>", styles['SmallBold']), Paragraph(init["description"], styles['TableCell'])],
            [Paragraph("<b>Goal</b>", styles['SmallBold']), Paragraph(init["goal"], styles['TableCell'])],
            [Paragraph("<b>Metrics</b>", styles['SmallBold']), Paragraph(init["metrics"], styles['TableCell'])],
        ]
        t = Table(table_data, colWidths=[120, 360])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), ACCENT),
            ('SPAN', (0, 0), (-1, 0)),
            ('BACKGROUND', (0, 1), (0, -1), LIGHT_GRAY),
            ('GRID', (0, 0), (-1, -1), 0.5, MEDIUM_GRAY),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ]))
        elements.append(KeepTogether([t, Spacer(1, 12)]))
    elements.append(PageBreak())
    return elements


def build_target_market(data, styles):
    elements = []
    tm = data["target_market"]
    elements.append(Paragraph("4. Target Market", styles['SectionTitle']))

    elements.append(Paragraph("Industries", styles['SubSection']))
    for ind in tm["industries"]:
        elements.append(Paragraph(f"<b>{ind['name']}</b>: {ind['description']}", styles['BodyText2']))

    elements.append(Paragraph("Buyer Personas", styles['SubSection']))
    for bp in tm["buyer_personas"]:
        elements.append(Paragraph(f"<b>{bp['name']}</b>: {bp['description']}", styles['BodyText2']))

    elements.append(Spacer(1, 12))
    elements.append(Paragraph("5. Competitive Analysis", styles['SectionTitle']))
    table_data = [[
        Paragraph("<b>Competitor</b>", styles['TableHeader']),
        Paragraph("<b>How We Compete</b>", styles['TableHeader']),
        Paragraph("<b>How We Win</b>", styles['TableHeader']),
    ]]
    for comp in tm["competitors"]:
        table_data.append([
            Paragraph(comp["name"], styles['TableCell']),
            Paragraph(comp["compete"], styles['TableCell']),
            Paragraph(comp["win"], styles['TableCell']),
        ])
    t = Table(table_data, colWidths=[120, 180, 180])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), ACCENT),
        ('BACKGROUND', (0, 1), (-1, -1), WHITE),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [WHITE, LIGHT_GRAY]),
        ('GRID', (0, 0), (-1, -1), 0.5, MEDIUM_GRAY),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
    ]))
    elements.append(t)
    elements.append(PageBreak())
    return elements


def build_market_strategy(data, styles):
    elements = []
    ms = data["market_strategy"]
    elements.append(Paragraph("6. Market Strategy", styles['SectionTitle']))
    for key in ["product", "price", "promotion", "people", "process"]:
        elements.append(Paragraph(f"<b>{key.title()}</b>", styles['SubSection']))
        elements.append(Paragraph(ms[key], styles['BodyText2']))
    elements.append(PageBreak())
    return elements


def build_budget(data, styles):
    elements = []
    budget = data["budget"]
    elements.append(Paragraph("7. Budget", styles['SectionTitle']))

    # Budget Table
    table_data = [[
        Paragraph("<b>Marketing Expense</b>", styles['TableHeader']),
        Paragraph("<b>Estimated Price</b>", styles['TableHeader']),
    ]]
    for exp in budget["expenses"]:
        table_data.append([
            Paragraph(exp["name"], styles['TableCell']),
            Paragraph(f"${exp['amount']:,.0f}", styles['TableCell']),
        ])
    table_data.append([
        Paragraph("<b>TOTAL</b>", styles['SmallBold']),
        Paragraph(f"<b>${budget['total']:,.0f}</b>", styles['SmallBold']),
    ])
    t = Table(table_data, colWidths=[300, 180])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), ACCENT),
        ('BACKGROUND', (0, -1), (-1, -1), LIGHT_GRAY),
        ('ROWBACKGROUNDS', (0, 1), (-1, -2), [WHITE, LIGHT_GRAY]),
        ('GRID', (0, 0), (-1, -1), 0.5, MEDIUM_GRAY),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 20))

    # Pie Chart
    d = Drawing(400, 220)
    pie = Pie()
    pie.x = 100
    pie.y = 20
    pie.width = 180
    pie.height = 180
    pie.data = [e["amount"] for e in budget["expenses"]]
    pie.labels = [e["name"] for e in budget["expenses"]]
    for i, c in enumerate(CHART_COLORS[:len(budget["expenses"])]):
        pie.slices[i].fillColor = c
        pie.slices[i].strokeColor = WHITE
        pie.slices[i].strokeWidth = 2
    pie.slices[0].popout = 8
    pie.sideLabels = True
    pie.simpleLabels = False
    d.add(pie)
    d.add(String(200, 205, "Budget Allocation", fontSize=12, fillColor=DARK_TEXT, fontName="Helvetica-Bold", textAnchor="middle"))
    elements.append(d)
    elements.append(PageBreak())
    return elements


def build_channels(data, styles):
    elements = []
    channels = data["marketing_channels"]
    elements.append(Paragraph("8. Marketing Channels", styles['SectionTitle']))

    table_data = [[
        Paragraph("<b>Channel</b>", styles['TableHeader']),
        Paragraph("<b>Purpose</b>", styles['TableHeader']),
        Paragraph("<b>Metrics</b>", styles['TableHeader']),
        Paragraph("<b>Target</b>", styles['TableHeader']),
    ]]
    for ch in channels:
        table_data.append([
            Paragraph(ch["name"], styles['TableCell']),
            Paragraph(ch["purpose"], styles['TableCell']),
            Paragraph(ch["metrics"], styles['TableCell']),
            Paragraph(f"{ch['target_value']:,}", styles['TableCell']),
        ])
    t = Table(table_data, colWidths=[90, 160, 140, 80])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), ACCENT),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [WHITE, LIGHT_GRAY]),
        ('GRID', (0, 0), (-1, -1), 0.5, MEDIUM_GRAY),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 20))

    # Bar Chart
    d = Drawing(420, 220)
    bc = VerticalBarChart()
    bc.x = 60
    bc.y = 30
    bc.height = 150
    bc.width = 320
    bc.data = [[ch["target_value"] for ch in channels]]
    bc.categoryAxis.categoryNames = [ch["name"] for ch in channels]
    bc.categoryAxis.labels.fontName = "Helvetica"
    bc.categoryAxis.labels.fontSize = 8
    bc.valueAxis.valueMin = 0
    bc.valueAxis.valueMax = max(ch["target_value"] for ch in channels) * 1.2
    bc.valueAxis.labels.fontName = "Helvetica"
    bc.valueAxis.labels.fontSize = 8
    for i in range(len(channels)):
        bc.bars[0].fillColor = CHART_COLORS[i % len(CHART_COLORS)]
    bc.bars.strokeColor = None
    bc.barWidth = 40
    d.add(bc)
    d.add(String(220, 195, "Channel Target Values", fontSize=12, fillColor=DARK_TEXT, fontName="Helvetica-Bold", textAnchor="middle"))
    elements.append(d)
    elements.append(PageBreak())
    return elements


def build_technology(data, styles):
    elements = []
    elements.append(Paragraph("9. Marketing Technology", styles['SectionTitle']))
    table_data = [[
        Paragraph("<b>Tool</b>", styles['TableHeader']),
        Paragraph("<b>Category</b>", styles['TableHeader']),
        Paragraph("<b>Description</b>", styles['TableHeader']),
    ]]
    for tech in data["marketing_technology"]:
        table_data.append([
            Paragraph(tech["name"], styles['TableCell']),
            Paragraph(tech["category"], styles['TableCell']),
            Paragraph(tech["description"], styles['TableCell']),
        ])
    t = Table(table_data, colWidths=[110, 100, 270])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), ACCENT),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [WHITE, LIGHT_GRAY]),
        ('GRID', (0, 0), (-1, -1), 0.5, MEDIUM_GRAY),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
    ]))
    elements.append(t)
    return elements


def generate_report(json_path, output_path):
    data = load_data(json_path)
    styles = get_styles()

    doc = SimpleDocTemplate(
        output_path, pagesize=A4,
        leftMargin=50, rightMargin=50,
        topMargin=60, bottomMargin=50,
        title=f"{data['company']['name']} Marketing Plan",
        author=", ".join([a["name"] for a in data["authors"]])
    )

    elements = []
    elements += build_cover_page(data, styles)
    elements += build_toc(styles)
    elements += build_business_summary(data, styles)
    elements += build_swot(data, styles)
    elements += build_initiatives(data, styles)
    elements += build_target_market(data, styles)
    elements += build_market_strategy(data, styles)
    elements += build_budget(data, styles)
    elements += build_channels(data, styles)
    elements += build_technology(data, styles)

    doc.build(elements, onFirstPage=header_footer, onLaterPages=header_footer)
    print(f"[OK] Report generated: {output_path}")
    return output_path


if __name__ == "__main__":
    script_dir = os.path.dirname(os.path.abspath(__file__))
    base_dir = os.path.dirname(script_dir)
    json_file = sys.argv[1] if len(sys.argv) > 1 else os.path.join(base_dir, "data", "sample_marketing_plan.json")
    output_file = sys.argv[2] if len(sys.argv) > 2 else os.path.join(base_dir, "output", "Marketing_Plan_Report.pdf")
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    generate_report(json_file, output_file)
